### ISSUE TITLE
SqlCeDatabaseCreator - CreateTables / HasTables do not tell the "truth"

### ISSUE THREAD

**Issue by hkoestin** [ErikEJ/EntityFramework7.SqlServerCompact#205] opened 2015-08-18 15:07 UTC
When having two different DbContext instances, e.g. A and B, both having different tables, e.g. A has a1 and a2, B has b1 and b2, a call to context.Database.EnsureCreated() does not really work, when both of the context instances point to the same DB file.

Only the tables of the first context will be created.

So, if you call contextA.EnsureCreated() first, tables a1 and a2 will be created. That is fine. However, when you want to use the same DB file for contextB as well, contextB.EnsureCreated() will not work anymore, because the "HasTables" method will simply say "true", because there are OTHER tables (namely a1 and a2) existing in the DB, but not b1 and b2.

The creator should also work in this case in my opinion.

HasTables should check, if the tables for the current model are given or not.
CreateTables should then create the tables, if needed.

Would this be possible?
Is this actually possible without any big side-effects?

**Comment by ErikEJ** [comment] 2015-08-18 15:39
I think this is a general design issue/bug, it looks like the SQL Server provider works in the exact same manner. Would be great if your could share a minimal piece of code demonstrating the issue. And maybe you could also test it with the SQL Server provider?

**Comment by bricelam** [comment] 2015-08-18 16:19
Yes, this is the behavior of EF by design. `HasTables()` means simply, *Does the database have any tables?* We were aware of the additional complexity this would add to applications targeting the same database with multiple DbContexts. `EnsureCreated()` is primarily for testing on relational providers; our recommended schema creation story there is Migrations. Please file [an issue on EF](https://github.com/aspnet/EntityFramework/issues/new), however, to discuss. We'd love to hear feedback in this area!

**Comment by hkoestin** [comment] 2015-08-19 07:30
@ErikEJ Thanks for pointing me to the referenced issue on the EF issue tracker. 

So here is a minimal piece of code, testing the issue on SQL CE:

Contexts (basically taken from the examples and just copied a second context):
```c#
public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    public BloggingContext(DbContextOptions options) : base(options)
    {
    }
}

public class SomeContext : DbContext
{
    public DbSet<Some> Some { get; set; }

    public SomeContext(DbContextOptions options) : base(options)
    {
    }
}

public class Some
{
    [Key]
    public int SomeId { get; set; }

    public string SomeField { get; set; }
}

public class Blog
{
    [Key]
    public int BlogId { get; set; }

    public string Url { get; set; }

    public List<Post> Posts { get; set; }
}

public class Post
{
    [Key]
    public int PostId { get; set; }

    public string Title { get; set; }
    public string Content { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

The "app":
```c#
var connectionBlogging = new SqlCeConnection(@"Data Source=Blogging.sdf");
var bloggingOptionsBuilder = new DbContextOptionsBuilder();
bloggingOptionsBuilder.UseSqlCe(connectionBlogging);

var bloggingOptions = bloggingOptionsBuilder.Options;

using (var x = new BloggingContext(bloggingOptions))
{
    // at the first run, this returns True
    Console.WriteLine("BloggingContext EnsureCreated: " + x.Database.EnsureCreated()); 
}

// use the same DB file again, but create a different context in it
using (var x = new SomeContext(bloggingOptions))
{
    // this will return False
    Console.WriteLine("SomeContext EnsureCreated: " + x.Database.EnsureCreated()); 
}

using (var y = new SomeContext(bloggingOptions))
{
    y.Some.Add(new Some {SomeField = "Some-Field-" + Guid.NewGuid()});
    y.SaveChanges(); // --> throws {"The specified table does not exist. [ Some ]"}
}
```

Sorry, I haven't had enough time to play around with SQL Server though, but I guess it will be the same result, as this seems to be "by design".

@bricelam I will definitely file an issue on the EF tracker. For me, it seems to be totally fine to let point to different DbContexts to the same phyiscal DB. I only have to ensure, that I am mapping my entities to different tables.

**Comment by hkoestin** [comment] 2015-08-19 09:24
@ErikEJ tried with EntityFramework.SqlServer-7.0.0-beta6 now as well. Same behavior. Only the exception message is a little different: `Invalid object name 'Some'.`

**Comment by ErikEJ** [comment] 2015-08-28 11:17
Closing for now as "by design"

**Closed by ErikEJ** 2015-08-28 11:17 UTC
